# Generated by Django 5.0.2 on 2024-04-25 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='fd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lecturerecord'),
        ),
        migrations.AlterField(
            model_name='lecturerecord',
            name='lr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
